#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fuck () {
  TF_PREVIOUS=$(fc -ln -1 | tail -n 1);
  TF_CMD=$(
    TF_ALIAS=fuck
    TF_SHELL_ALIASES=$(alias)
    PYTHONIOENCODING=utf-8
    thefuck $TF_PREVIOUS THEFUCK_ARGUMENT_PLACEHOLDER $*
  ) && eval $TF_CMD;
  test -n "$TF_CMD" && print -s $TF_CMD
}

alias damn="fuck"
alias dammit="fuck"
alias shit="fuck"
